name: Primeiro Workflow

on:
  push:

jobs: 
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar data
        run: date

      - name: Mostrar diretório
        run: pwd

      - name: Baixar repo
        run: git clone https://github.com/leandromqs/devops-lab

      - name: Listar arquivos
        run: ls -la
